"""Scan configuration: what to ignore, and how to classify files.

False positives destroy trust in an audit tool faster than missed findings, so
classification lives here in one auditable place. We exclude lockfiles, minified
bundles, generated files, and vendored trees, and we recognize test/config/story
files as legitimate non-imported entrypoints rather than "orphans".

A repo may add a ``.saignore`` (one fnmatch glob per line, ``#`` comments) to
extend the ignore set without code changes.
"""

from __future__ import annotations

import fnmatch
from dataclasses import dataclass, field
from pathlib import Path

# Paths never worth scanning for findings (size still counts toward totals).
DEFAULT_IGNORE_GLOBS = (
    "*.lock", "*-lock.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "*.min.js", "*.min.css", "*.map", "*.snap",
    "*.svg", "*.ico", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp", "*.woff*", "*.ttf",
    "*.pdf", "*.mp4", "*.mov", "*.zip", "*.gz",
    "CHANGELOG*", "*.generated.*", "*.gen.ts", "*.d.ts",
)

# Tree fragments that are vendored or generated even when tracked in-repo.
DEFAULT_IGNORE_DIR_FRAGMENTS = (
    "/vendor/", "/third_party/", "/third-party/", "/.vendor/",
    "/generated/", "/__generated__/", "/.generated/",
)

# Filename stems that are entrypoints by convention (run, not imported).
ENTRYPOINT_BASENAMES = frozenset({
    "page", "layout", "route", "loading", "error", "not-found", "template",
    "middleware", "next.config", "tailwind.config", "vitest.config", "playwright.config",
    "postcss.config", "eslint.config", "jest.config", "index", "main", "globals",
    "instrumentation", "opengraph-image", "sitemap", "robots", "manifest", "head",
    "default", "global-error", "setup", "conftest",
})

TEST_MARKERS = (".test.", ".spec.", ".stories.", ".bench.", ".e2e.", "_test.")
TEST_DIR_FRAGMENTS = ("/tests/", "/test/", "/__tests__/", "/e2e/", "/cypress/", "/.storybook/")

GENERATED_MARKERS = (
    "@generated", "do not edit", "auto-generated", "autogenerated",
    "code generated", "this file is generated", "generated by",
)


@dataclass
class ScanConfig:
    ignore_globs: tuple[str, ...] = DEFAULT_IGNORE_GLOBS
    ignore_dir_fragments: tuple[str, ...] = DEFAULT_IGNORE_DIR_FRAGMENTS
    extra_ignores: list[str] = field(default_factory=list)

    @classmethod
    def load(cls, repo: Path) -> "ScanConfig":
        cfg = cls()
        saignore = repo / ".saignore"
        if saignore.exists():
            try:
                for line in saignore.read_text().splitlines():
                    line = line.strip()
                    if line and not line.startswith("#"):
                        cfg.extra_ignores.append(line)
            except OSError:
                pass
        return cfg

    def is_ignored(self, relpath: str) -> bool:
        name = relpath.rsplit("/", 1)[-1]
        posix = "/" + relpath.replace("\\", "/")
        for frag in self.ignore_dir_fragments:
            if frag in posix:
                return True
        for pat in self.ignore_globs:
            if fnmatch.fnmatch(name, pat):
                return True
        for pat in self.extra_ignores:
            if fnmatch.fnmatch(name, pat) or fnmatch.fnmatch(relpath, pat):
                return True
        return False


# Subtrees whose internals are vendored/implementation code: counted for size
# and scanned for references, but never flagged for refactoring (you do not
# restructure someone else's installed skill or plugin).
VENDOR_FINDING_FRAGMENTS = ("/.claude/skills/", "/.claude/plugins/", "/.cursor/")


def is_vendored_for_findings(relpath: str) -> bool:
    posix = "/" + relpath.replace("\\", "/")
    return any(frag in posix for frag in VENDOR_FINDING_FRAGMENTS)


def is_test_file(relpath: str) -> bool:
    name = relpath.rsplit("/", 1)[-1]
    posix = "/" + relpath.replace("\\", "/")
    if any(m in name for m in TEST_MARKERS):
        return True
    return any(frag in posix for frag in TEST_DIR_FRAGMENTS)


def is_config_file(stem: str) -> bool:
    return stem in ENTRYPOINT_BASENAMES or stem.endswith(".config") or stem.startswith(".")


def looks_generated(text_head: str) -> bool:
    head = text_head[:1500].lower()
    return any(m in head for m in GENERATED_MARKERS)


def looks_minified(text: str, sample: int = 4000) -> bool:
    chunk = text[:sample]
    if not chunk:
        return False
    lines = chunk.splitlines() or [chunk]
    longest = max((len(ln) for ln in lines), default=0)
    avg = sum(len(ln) for ln in lines) / max(1, len(lines))
    return longest > 2000 or avg > 350
